import { ReactNode } from "react";
import "./globals.css";
import type { Metadata } from "next";
import { IconFileMusic, IconHeart } from "@tabler/icons-react";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Musescore PDF Generator",
  description: "Generated by create next app",
};

type Props = { children: ReactNode };

export default function Layout({ children }: Props) {
  return (
    <html lang="en">
      <body className="mx-auto flex min-h-screen max-w-5xl flex-col p-8">
        <header className="flex items-center gap-2">
          <Link href="/" tabIndex={-1}>
            <IconFileMusic size={48} />
          </Link>

          <div>
            <Link href="/">
              <h1 className="text-2xl font-bold">Musescore PDF Generator</h1>
            </Link>

            <p className="text-muted-foreground">
              Please ensure that you are complying with{" "}
              <a
                href="https://musescore.com/download-terms"
                target="_blank"
                className="underline underline-offset-2 transition-colors hover:text-muted-foreground/80"
              >
                Musescore&apos;s download terms
              </a>{" "}
              before using this tool.
            </p>
          </div>
        </header>

        <hr className="my-4 border-border" />

        {children}

        <hr className="my-4 mt-16 border-border" />

        <footer className="flex flex-col items-center gap-2">
          <p className="text-center text-muted-foreground">
            Made with <IconHeart size={16} className="mb-1 inline" /> by{" "}
            <a
              href="https://zsrobinson.com/"
              target="_blank"
              className="underline underline-offset-2 transition-colors hover:text-muted-foreground/80"
            >
              Zachary Robinson
            </a>{" "}
            · View this project on{" "}
            <a
              href="https://github.com/zsrobinson/musescore-pdf/"
              target="_blank"
              className="underline underline-offset-2 transition-colors hover:text-muted-foreground/80"
            >
              GitHub
            </a>
          </p>
        </footer>
      </body>
    </html>
  );
}
